//EEPROM ADDRESSES
#define ABS_X_COORD_EEPROM_ADDRESS 1
#define ABS_Y_COORD_EEPROM_ADDRESS 2
#define ABS_Z_COORD_EEPROM_ADDRESS 3

//X-Axis
#define DISTANCE_PER_REV_X_AXIS 32
#define STEPS_PER_REV_X_AXIS 1600
#define MAX_FEEDRATE_X_AXIS 3000

//Y-Axis
#define DISTANCE_PER_REV_Y_AXIS 32
#define STEPS_PER_REV_Y_AXIS 1600
#define MAX_FEEDRATE_Y_AXIS 3000

//Z-Axis
#define DISTANCE_PER_REV_Z_AXIS 32
#define STEPS_PER_REV_Z_AXIS 1600
#define MAX_FEEDRATE_Z_AXIS 3000